version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:18.04-scm-browsers-legacy
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t test-image .
