version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    environment:
      DOCKER_HOST: tcp://localhost:2375
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image .
      - run:
          name: Tag Docker image
          command: |
            docker tag my-image:latest klentytestacr.azurecr.io/my-image:latest
      - run:
          name: Push Docker image
          command: |
            docker login klentytestacr.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push klentytestacr.azurecr.io/my-image:latest
