
version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run: docker build -t myimage:${CIRCLE_SHA1} .

  push:
    docker:
      - image: docker:19.03.12
    environment:
      IMAGE_NAME: klentytestacr.azurecr.io/myimage:${CIRCLE_SHA1}
      DOCKER_HOST: tcp://localhost:2375
      DOCKER_DRIVER: overlay2
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: "Login to Azure"
          command: |
            docker login klentytestacr.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
      - run:
          name: "Tag and Push Docker image"
          command: |
            docker tag myimage:${CIRCLE_SHA1} $IMAGE_NAME
            docker push $IMAGE_NAME

workflows:
  version: 2
  build-and-push:
    jobs:
      - build
      - push:
          requires:
            - build
