version: 2.1
jobs:
  nginx:          
    docker:
      - image: circleci/node:14  
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Tools & Login to AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get install docker
      - run:
          name: Build Docker Image & Push to ACR
          command: |
            docker build -t nginx-image -f Dockerfile.nginx .
            docker tag nginx-image:latest $ACR_REGISTRY.azurecr.io/nginx-image:latest
            docker login $ACR_REGISTRY.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push $ACR_REGISTRY.azurecr.io/nginx-image:latest


workflows:
  nginx-and-apache:
    jobs:
      - nginx