version: 2.1
jobs:
  nginx:          
    machine:
      enabled: true
    environment:
      DOCKER_HOST: tcp://40.76.91.132:2375
    steps:
      - checkout
      - run: 
          name: Install Tools & Login to AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get install docker
      - run:
          name: Build Docker Image & Push to ACR
          command: |
            docker build -t $REGISTRY_URL/nginx-image -f Dockerfile.nginx .
            docker login $REGISTRY_URL -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push $REGISTRY_URL/nginx-image:latest


workflows:
  nginx-and-apache:
    jobs:
      - nginx