version: 2.1
jobs:
  nginx:          
    docker:
      - image: circleci/node:14  
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Install Tools & Login to AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get install docker
      - run:
          name: Build Docker Image & Push to ACR
          command: |
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az acr login --name $REGISTRY_NAME
            docker build -t nginx-image -f Dockerfile.nginx .
            docker tag nginx-image:latest $REGISTRY_NAME.azurecr.io/nginx-image:latest
            docker push $REGISTRY_NAME.azurecr.io/nginx-image:latest


workflows:
  nginx-and-apache:
    jobs:
      - nginx