version: 2.1
jobs:
  nginx:          
    machine:
      enabled: true
    environment:
      DOCKER_HOST: tcp://20.172.229.168:2375
    steps:
      - checkout
      - run: 
          name: Install Tools & Login to AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get install docker
            curl -O https://s3.us-west-2.amazonaws.com/amazon-eks/1.24.10/2023-01-30/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
            az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME
      - run:
          name: Build Docker Image & Push to ACR
          command: |
            docker build -t $REGISTRY_URL/nginx-image -f Dockerfile.nginx .
            docker login $REGISTRY_URL -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push $REGISTRY_URL/nginx-image:latest
      - run:
          name: Deploy into AKS
          command: |  
            echo $KUBECONFIG | base64 --decode > ~/.kube/config
            kubectl apply -f nginx_deploy.yaml


workflows:
  nginx-and-apache:
    jobs:
      - nginx