version: 2.1
jobs:
  build:
    docker:
      - image: docker:19.03.12 
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t test-image -f Dockerfile.nginx .
