version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t nginx-image -f Dockerfile.nginx .
            docker build -t apache-image -f Dockerfile.apache .
      - run:
          name: Tag Docker image
          command: |
            docker tag nginx-image:latest klentytestacr.azurecr.io/nginx-image:latest
            docker tag apache-image:latest klentytestacr.azurecr.io/apache-image:latest
      - run:
          name: Push Docker image
          command: |
            docker login klentytestacr.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push klentytestacr.azurecr.io/nginx-image:latest
            docker push klentytestacr.azurecr.io/apache-image:latest   
