version: 2.1
jobs:
  build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image -f Dockerfile.nginx .
      - run:
          name: Tag Docker image
          command: |
            docker tag my-image:latest klentytestacr.azurecr.io/my-image:latest
      - run:
          name: Push Docker image
          command: |
            docker login klentytestacr.azurecr.io -u $ACR_USERNAME -p $ACR_PASSWORD
            docker push klentytestacr.azurecr.io/my-image:latest    
  deploy:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - run: |
          az account set --subscription $SUBSCRIPTION_ID
          az aks get-credentials --resource-group $RESOURCE_GROUP --name $CLUSTER_NAME
          kubectl apply -f nginx_deploy.yaml
          kubectl apply -f nginx_svc.yaml    
