version: 2.1
jobs:
  nginx:          
    machine:
      enabled: true
    environment:
      DOCKER_HOST: tcp://40.76.91.132:2376
    steps:
      - run: 
          name: Install Tools & Login to AKS
          command: |
            sudo apt-get update
            curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            sudo apt-get install docker
      - run:
          name: Build Docker Image & Push to ACR
          command: |
            docker login -u $ACR_USERNAME -p $ACR_PASSWORD
            docker build -t nginx-image -f Dockerfile.nginx .
            docker tag nginx-image:latest $REGISTRY_NAME.azurecr.io/nginx-image:latest
            docker push $REGISTRY_NAME.azurecr.io/nginx-image:latest


workflows:
  nginx-and-apache:
    jobs:
      - nginx